[workspace]
resolver = "3"
members = [
    "inventium",
    "expedio",
    "procurator",
    "packust"
]

[workspace.dependencies]
anyhow = "1.0.100"
reqwest = "0.12.24"
serde = "1.0.228"
tokio = "1.48.0"