[package]
name = "expedio"
version = "0.0.1"
edition = "2024"
authors = ["Oganesson897 <oganesson897@gmail.com>"]
description = "NEO Minecraft Modpack Format & Format Converter"
repository = "https://github.com/ElectronicWave/Packust"
license = "AGPL-3"